// All these are action types and not actions
export const AUTH_ACTIONS = {
  IS_LOGGING_IN: 'IS_LOGGING_IN',
  LOGIN: 'LOGIN',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGOUT: 'LOGOUT',
};

export const HOME_ACTIONS = {
  IS_LOADING_POSTS: 'IS_LOADING_POSTS',
  SET_POST_DATA: 'SET_POST_DATA',
  ERROR_POSTS: 'ERROR_POSTS',
};

export const TODO_ACTIONS = {
  IS_LOADING_LIST: 'IS_LOADING_LIST',
  SET_TODO_LIST: 'SET_TODO_LIST',
  ERROR_LIST: 'ERROR_LIST',
};
